config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "items#index"
  resources :items, only: [:new, :create, :show, :edit, :update] do
    resources :comments, only: :create
   end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: 'レディース' },
    { id: 2, name: 'メンズ' },
    { id: 3, name: 'ベビー・キッズ' },
    { id: 4, name: 'インテリア・住まい・小物' },
    { id: 5, name: '本・音楽・ゲーム' },
    { id: 6, name: 'おもちゃ・ホビー・グッズ' },
    { id: 7, name: '家電・スマホ・カメラ' },
    { id: 8, name: 'スポーツ・レジャー' },
    { id: 9, name: 'ハンドメイド' },
    { id: 10, name: 'その他' }
  ]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  belongs_to :user
  has_one_attached :image
  belongs_to_active_hash :category
  has_many :comments

  with_options presence: true do
    validates :image
    validates :name
    validates :price
  end

  validates :category_id, numericality: { greater_than_or_equal_to:1 ,less_than_or_equal_to:10, message: "is invalid" }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :nickname, presence: true
  has_many :items
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @item = Item.find(params[:item_id]) #追加
    if @comment.save
      CommentChannel.broadcast_to @item, { comment: @comment, user: @comment.user } #追加
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, item_id: params[:item_id])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update]
  before_action :set_item, only: [:show, :edit, :update]
  before_action :redirect_to_show, only: [:edit, :update]

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comments = @item.comments.includes(:user)
    @comment = Comment.new
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private
  def item_params
    params.require(:item).permit(:name, :image, :category_id, :price).merge(user_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def redirect_to_show
    return redirect_to root_path if current_user.id != @item.user.id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_with model: @item, id: 'new_item', local: true do |f| %>
<%= render 'shared/error_messages', model: f.object %>
  <div class="name-field">
    <span>■ 名前</span>
    <%= f.text_field :name %>
  </div>
  <div class="image-field">
    <span>■ 画像</span>
    <div class="click-upload">
      <%= f.file_field :image %>
    </div>
  </div>
    <div class="category-field">
      <span>■ カテゴリー</span>
      <%= f.collection_select :category_id, Category.all, :id, :name, {include_blank: "---"} %>
    </div>
    <div class="pricefield">
      <span>■ 価格</span>
      <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"半角数字で入力" %>
    </div>
  <div class="submit-btn">
    <%= f.submit '送信' %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h3>編集ページ</h3>
<%= render partial: 'form' %>

app/views/items/index.html.erb
<%= render "shared/header" %>
<h3>トップページ</h3>
<h3><%= link_to '商品出品', new_item_path%></h3>
<% @items.each do |item| %>
  <div class="posted-content">
    <%= image_tag item.image %><br>
    <%= item.name%><br>
    <%= link_to '詳細', item_path(item.id)%>
  </div>
<% end %>

app/views/items/new.html.erb
<h3>新規投稿ページ</h3>
<%= render partial: "form" %>

app/views/items/show.html.erb
<h3>詳細ページ</h3>
<div class="posted-content">
  <%= image_tag @item.image %><br>
  <table>
    <tr>
      <td>商品名</td>
      <td><%= @item.name%></td>
    </tr>
    <tr>
      <td>カテゴリー</td>
      <td><%= @item.category.name%></td>
    </tr>
    <tr>
      <td>価格</td>
      <td><%= @item.price%></td>
    </tr>
    <tr>
  </table>
  <% if user_signed_in? && current_user.id == @item.user_id%>
    <%= link_to '編集', edit_item_path(@item.id)%>
  <% end %>
</div>

<div id="comments">
  <h4>＜コメント一覧＞</h4>
    <% @item.comments.each do |comment| %>
      <div class="comment">
        <p class="user-info"><%= comment.user.nickname %>： </p>
        <p><%= comment.text%></p>
      </div>
    <% end %>
</div>

<div class="comment-form">
  <% if user_signed_in? %>
    <%= form_with model: [@item, @comment], id: "comment-form" do |f| %>
      <%= f.text_area :text , class: "comment-text"%>
      <%= f.submit "コメントをする", class: "comment-submit" %>
    <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CommentAppRails7</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_header.html.erb
<header class='top-page-header'>
  <div class='nav'>
    <ul class='lists'>
      <% if user_signed_in? %>
      <li class="user_name" >ユーザー名： <%= "#{current_user.nickname}" %></li>
      <li class="logout" ><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
      <% else %>
      <li class="login"><%= link_to 'ログイン', new_user_session_path %></li>
      <li class="sign-up"><%= link_to '新規登録', new_user_registration_path %></li>
      <% end %>
    </ul>
  </div>
</header>